### ISSUE TITLE
ProtocolLib is not working properly for me, the plugins that require protocolLib are not loading

### ISSUE THREAD

**Issue by LilMaconha** [dmulloy2/ProtocolLib#2028]
Here is the error I get:
https://mcpaste.com/3b574477a5fb873446d228f5e1f1505a

**Comment by Brokkonaut** [comment]
It is not yet updated for 1.19.3

**Comment by VoltroXP** [comment]
This is a BIG problem, as it is basically making it impossible for anyone (including myself) to join the server.

**Comment by dmulloy2** [comment]
should be fixed in latest dev build

**Comment by VoltroXP** [comment]
> 

I'm still having issues joining my server with the latest dev build. It gives this error [ERROR] Packet encoding of packet ID 78 threw (skippable? false)
