### ISSUE TITLE
Add conversion methods to Wire Packets

### ISSUE THREAD

**Issue by MineTheCube** [dmulloy2/ProtocolLib#224]
Hi,

I hope this is the right place to get help. Well I want to make 1.10 clients see a Polar Bear where there is a Pig (that 1.8 and 1.9 client will see). I use ViaVersion in order to accept multiple client version, so it may interfere with what I try to achieve.

What I've done is intercepting the `PacketPlayOutSpawnEntityLiving` packet, and changing the Entity Type (int) from 90 to 102. But the client is kicked as soon I change this packet. I tried to change it to a cow (90 → 92), it works (I see a cow).

So I think I may be a serialization issue, where server is unable to handle entity type 102, maybe you have any idea of how I can achieve it ?

Server log:

```
[00:39:41 INFO]: MTC lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
```

My code:

``` java
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(plugin, PacketType.Play.Server.SPAWN_ENTITY_LIVING) {

    @Override
    public void onPacketSending(PacketEvent event) {
        if (event.getPacket().getIntegers().read(1) == 90) {
            event.setCancelled(true);

            PacketContainer packet = event.getPacket().deepClone();
            packet.getIntegers().write(1, 102);

            try {
                ProtocolLibrary.getProtocolManager().sendServerPacket(event.getPlayer(), packet);
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }                   
        }
    }
});
```

And /protocol dump for additional information: http://pastebin.com/raw/UFGAN8Jz

**Comment by dmulloy2** [comment]
If I had to wager a guess it has to do with ViaVersion.

Although there's more to that stack trace. Try setting ````debug=true```` in the server.properties and providing the rest.

**Comment by MineTheCube** [comment]
Yeah you were right, it's due to ViaVersion: [pastebin.com/DSfRRU6e](http://pastebin.com/raw/DSfRRU6e)

Well with ViaVersion I can send raw packet (so I think without using his remapper): with [sendRawPacket(Player, Bytebuf)](https://jd.viaversion.com/us/myles/ViaVersion/api/ViaVersionAPI.html#sendRawPacket(org.bukkit.entity.Player,%20io.netty.buffer.ByteBuf)). But how can I convert a protocollib's packet to a bytebuf ?

**Comment by dmulloy2** [comment]
It requires a bit of NMS, but you could create a PacketDataSerializer (which is conveniently a ByteBuf) and use the packet's serialize method. Something like this:

````java
PacketDataSerializer serializer = new PacketDataSerializer(Unpooled.buffer());
Packet nmsPacket = (Packet) packet.getHandle();
nmsPacket.b(serializer);
// Send with ViaVersion
````

You know that would probably be pretty easy to implement in ProtocolLib itself now that I think about it.

**Comment by MineTheCube** [comment]
Ok thanks, but now client is disconnected for `Bad packet id XX`, where XX seems to change each time I compile my plugin. 

Also, it happens even if I don't change packet data at all:
```java
if (event.getPacket().getIntegers().read(1) == 90 && ViaVersion.getInstance().getPlayerVersion(event.getPlayer()) == 210) {
    event.setCancelled(true);

    PacketDataSerializer serializer = new PacketDataSerializer(Unpooled.buffer());
    Packet nmsPacket = (Packet) event.getPacket().getHandle();

    try {
        nmsPacket.b(serializer);
        ViaVersion.getInstance().sendRawPacket(event.getPlayer(), serializer);
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

**Comment by dmulloy2** [comment]
You have to encode the packet id first:
````java
serializer.d(event.getPacketId());
nmsPacket.b(serializer);
````

**Comment by MineTheCube** [comment]
Well, it still doesn't work.. 

I've this error client side:
![](http://i.imgur.com/OngZfEu.png)

And server side it is just a "lost connection: Disconnected".

Here is my code:
```java
PacketContainer packet = event.getPacket().deepClone();
PacketDataSerializer serializer = new PacketDataSerializer(Unpooled.buffer());
Packet nmsPacket = (Packet) packet.getHandle();

try {
    serializer.b(event.getPacketID());
    nmsPacket.b(serializer);
    ViaVersion.getInstance().sendRawPacket(event.getPlayer(), serializer);
} catch (IOException e) {
    e.printStackTrace();
}
```

**Comment by dmulloy2** [comment]
Try the latest dev build and this code:
````java
PacketContainer packet = event.getPacket().deepClone();
WirePacket wire = WirePacket.fromPacket(packet);
ByteBuf buffer = wire.serialize();

try {
    ViaVersion.getInstance().sendRawPacket(event.getPlayer(), buffer);
} catch (IOException ex) {
    ex.printStackTrace();
}

**Comment by MineTheCube** [comment]
The latest build doesn't seem to contain the new methods/classes, as I have `NoClassDefFoundError` on my server but compiling with the API works as expected.

**Comment by dmulloy2** [comment]
Ah, I must've forgotten to include the latest version of the API. Once the CI server's done being crashed, I'll fix that.

**Comment by MineTheCube** [comment]
New methods are in build 308 as expected, but now I've a [`ClassNotFoundException: net.minecraft.server.v1_8_R3.DataWatcherObject`](http://pastebin.com/raw/BQjVgPXM)..

**Comment by dmulloy2** [comment]
Should be fixed in the latest dev build.

**Comment by MineTheCube** [comment]
Thanks for investing so much time in my issue.
But sadly it is still not working: http://pastebin.com/raw/qbzrym66

**Comment by MineTheCube** [comment]
So now it throws an `UnsupportedOperationException: direct buffer` (http://pastebin.com/raw/6PhfFiYe)

**Comment by MineTheCube** [comment]
So I no longer have server side errors, but client disconnects with this:
![](http://i.imgur.com/leW26MN.png)

**Comment by dmulloy2** [comment]
Try setting ````debug=true```` and see if you can get a more informative error

**Comment by MineTheCube** [comment]
Here is the stacktrace: http://pastebin.com/raw/Z18P9fzy

**Comment by MineTheCube** [comment]
I'm now disconnected due to: `io.netty.handler.codec.DecoderException: Unknown serializer type 127`

Client in 1.12, server 1.8.8, using ViaVersion 1.1.1.

**Comment by Xemiru** [comment]
Was there any continuation to this? I'm having problems using wire packets even when ViaVersion is removed from the server; copying a simple chat packet and sending through wire kicks the client with that same DecoderException.

```
PacketContainer pc = new PacketContainer(PacketType.Play.Server.CHAT);
pc.getChatComponents().write(0, WrappedChatComponent.fromText("a"));
pc.getChatTypes().write(0, EnumWrappers.ChatType.CHAT);

WirePacket wire = WirePacket.fromPacket(pc);
for (Player p : Bukkit.getOnlinePlayers()) {
    try {
        ProtocolLibrary.getProtocolManager().sendWirePacket(p, wire);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

![image](https://user-images.githubusercontent.com/1240058/57954069-bd755b80-78a6-11e9-9265-84ae2886d27a.png)
