### ISSUE TITLE
Versions in repository are invalid

### ISSUE THREAD

**Issue by Yamakaja** [dmulloy2/ProtocolLib#355]
As you can see the version tag of
http://repo.dmulloy2.net/nexus/repository/public/com/comphenix/protocol/ProtocolLib/4.3.0/ProtocolLib-4.3.0.pom
is "${minorVersion}", which leads to compilation issues:

(Using gradle): "inconsistent module metadata found. Descriptor: com.comphenix.protocol:ProtocolLib:${minorVersion} Errors: bad version: expected='4.3.0' found='${minorVersion}'"

**Comment by dmulloy2** [comment]
It compiles just fine with Maven, maybe this is a Gradle-specific problem?

**Comment by Yamakaja** [comment]
It should be fixed either way

**Comment by initramfs** [comment]
Gradle performs additional validation on POM files to ensure they are valid and fails the build when they are not, this behaviour cannot be disabled. As you've currently set up the project, `ProtocolLib-API` gains an invalid version tag based on the current state of development of the project `ProtocolLib-Parent`.

Due to the way your project structure is set up `ProtocolLib-API` is a child of the parent `ProtocolLib-Parent`, whilst using it's parent's `minorVersion` property as it's own version. The problem with this approach is that the two projects/modules aren't versioned together, whilst `ProtocolLib-API` increments through 4.x.x, `ProtocolLib-Parent`'s version has been left at `v4-SNAPSHOT`. When a build system (be it Maven or Gradle) attempts to resolve dependencies, it will pull the declared version of `ProtocolLib-API` as defined (in the user's `POM.xml` or `build.gradle`), but additionally pull the latest version of `ProtocolLib-Parent`. As you can imagine, if `ProtocolLib-Parent` updates, the `minorVersion` property you've declared would also change. When a build system then tries to evaluate the version property in `ProtocolLib-API`, it consults the (much newer) `ProtocolLib-Parent` and gains whatever version was declared there. This is obvious incorrect, as effectively, this will make any version of `ProtocolLib-API` who inherits from `ProtocolLib-Parent` self-declare a version of whatever the latest version of `ProtocolLib-Parent` is.

The only reason Maven doesn't fail the build is because Maven doesn't recheck the version string on the POM file of the dependency (or if it does, it silently ignores the fact that the version is wrong).

To illustrate this point, my gradle stack trace shows (stack trace differs from @Yamakaja due to Gradle version used):

```java
> Could not resolve all files for configuration ':runtime'.
   > Could not resolve com.comphenix.protocol:ProtocolLib-API:4.3.0.
     Required by:
         project :
      > Could not resolve com.comphenix.protocol:ProtocolLib-API:4.3.0.
         > inconsistent module metadata found. Descriptor: com.comphenix.protocol:ProtocolLib-API:4.4.0-SNAPSHOT Errors: bad version: expected='4.3.0' found='4.4.0-SNAPSHOT'
```
The same trace appears for any version of `ProtocolLib-API` except for `4.4.0-SNAPSHOT` which is the latest version in your Maven repository at the time of writing.

Also, as an additional point, Maven actually warns you about this when compiling (though it's warning is a more generic 'don't use expressions as versions'):

```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.comphenix.protocol:ProtocolLib-API:jar:4.3.0
[WARNING] 'version' contains an expression but should be a constant. @ com.comphenix.protocol:ProtocolLib-API:${minorVersion}, /home/initramfs/IdeaProjects/Minecraft/HungerGames/dependencies/ProtocolLib/modules/API/pom.xml, line 6, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.comphenix.protocol:ProtocolLib:jar:4.3.0
[WARNING] 'version' contains an expression but should be a constant. @ com.comphenix.protocol:ProtocolLib:${minorVersion}, /home/initramfs/IdeaProjects/Minecraft/HungerGames/dependencies/ProtocolLib/modules/ProtocolLib/pom.xml, line 6, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
Resolving this issue would involve properly versioning `ProtocolLib-API` by inserting a hard-coded version string instead of the expression `${minorVersion}`.

**Comment by initramfs** [comment]
Any reason why this issue was closed without resolution? Issue still occurs to this date.
